name: Pressure Monitor

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  monitor-pressure:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run pressure monitor
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        IFTT_WEBHOOK_URL: ${{ secrets.IFTT_WEBHOOK_URL }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        COORDINATES: ${{ secrets.COORDINATES }}
      run: |
        python pressure_monitor.py
    
    - name: Upload logs (if available)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pressure-monitor-logs
        path: pressure_monitor.log
        retention-days: 7 